import { Project, Recommendation } from "@/types/project";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Brain, Cloud, MapPin, DollarSign, CheckCircle2, AlertTriangle, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

interface Props {
  project: Project;
  onApprove: () => void;
  onRefine?: () => void;
}

export const RecommendationReview = ({ project, onApprove, onRefine }: Props) => {
  const rec = project.recommendation;
  if (!rec) {
    return (
      <div className="text-center py-12 text-muted-foreground">
        <Sparkles className="h-10 w-10 mx-auto mb-2 opacity-30" />
        <p className="text-sm">No recommendation yet. Complete the Discovery chat first.</p>
      </div>
    );
  }

  const overBudget = rec.budgetTargetUsd !== null && rec.totalMonthlyCostUsd > rec.budgetTargetUsd;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h2 className="text-xl font-semibold flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-accent" />
            AI-Drafted Cloud Blueprint
          </h2>
          <p className="text-sm text-muted-foreground mt-0.5">
            Generated by Aria based on your discovery conversation.
          </p>
        </div>
        {rec.approved ? (
          <Badge className="bg-success/10 text-success border-success/30">
            <CheckCircle2 className="h-3 w-3 mr-1" /> Approved
          </Badge>
        ) : (
          <div className="flex gap-2">
            {onRefine && (
              <Button variant="outline" onClick={onRefine}>
                Refine via Chat
              </Button>
            )}
            <Button className="gradient-primary text-primary-foreground" onClick={onApprove}>
              <CheckCircle2 className="h-4 w-4 mr-1.5" />
              Approve & Continue
            </Button>
          </div>
        )}
      </div>

      {/* Verdict cards */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div className="bg-card border rounded-lg p-5 shadow-card">
          <div className="flex items-center gap-2 mb-3">
            <Brain className="h-4 w-4 text-accent" />
            <h3 className="text-xs uppercase tracking-wider font-semibold text-muted-foreground">
              Solution Type
            </h3>
          </div>
          <p className="text-lg font-bold">
            {rec.solutionType === "generative-ai" ? "Generative AI Environment" : "Standard Public Cloud"}
          </p>
          <ul className="mt-3 space-y-1.5">
            {rec.solutionRationale.map((r, i) => (
              <li key={i} className="text-xs text-muted-foreground flex gap-2">
                <span className="text-accent mt-0.5">•</span>
                <span>{r}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="bg-card border rounded-lg p-5 shadow-card">
          <div className="flex items-center gap-2 mb-3">
            <Cloud className="h-4 w-4 text-primary" />
            <h3 className="text-xs uppercase tracking-wider font-semibold text-muted-foreground">
              Recommended Provider
            </h3>
          </div>
          <p className="text-lg font-bold flex items-center gap-2">
            {rec.provider}
            <Badge variant="outline" className="text-[10px]">
              <MapPin className="h-2.5 w-2.5 mr-1" />
              {rec.region}
            </Badge>
          </p>
          <ul className="mt-3 space-y-1.5">
            {rec.providerRationale.map((r, i) => (
              <li key={i} className="text-xs text-muted-foreground flex gap-2">
                <span className="text-primary mt-0.5">•</span>
                <span>{r}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className={cn("border rounded-lg p-5 shadow-card", overBudget ? "bg-destructive/5 border-destructive/30" : "bg-card")}>
          <div className="flex items-center gap-2 mb-3">
            <DollarSign className={cn("h-4 w-4", overBudget ? "text-destructive" : "text-success")} />
            <h3 className="text-xs uppercase tracking-wider font-semibold text-muted-foreground">
              Estimated Monthly Cost
            </h3>
          </div>
          <p className="text-2xl font-bold">
            ${rec.totalMonthlyCostUsd.toLocaleString()}
            <span className="text-sm font-normal text-muted-foreground"> / mo</span>
          </p>
          {rec.budgetTargetUsd !== null && (
            <p className={cn("text-xs mt-2 flex items-center gap-1", overBudget ? "text-destructive" : "text-success")}>
              {overBudget ? <AlertTriangle className="h-3 w-3" /> : <CheckCircle2 className="h-3 w-3" />}
              {overBudget
                ? `Exceeds budget target of $${rec.budgetTargetUsd.toLocaleString()}/mo`
                : `Within budget target of $${rec.budgetTargetUsd.toLocaleString()}/mo`}
            </p>
          )}
        </div>
      </div>

      {/* Resource bucket */}
      <div className="bg-card border rounded-lg shadow-card overflow-hidden">
        <div className="px-5 py-3 border-b">
          <h3 className="font-semibold text-sm">Recommended Resource Bucket</h3>
          <p className="text-xs text-muted-foreground">These are the exact resources that will be raised via GPS / RFC and provisioned via Terraform.</p>
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Service</TableHead>
              <TableHead>Sizing</TableHead>
              <TableHead className="text-center">Count</TableHead>
              <TableHead className="text-right">Monthly Cost</TableHead>
              <TableHead>Rationale</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {rec.resources.map((r, i) => (
              <TableRow key={i}>
                <TableCell className="font-medium">{r.service}</TableCell>
                <TableCell className="text-muted-foreground text-xs">{r.sizing}</TableCell>
                <TableCell className="text-center">{r.count}</TableCell>
                <TableCell className="text-right font-mono">
                  ${(r.monthlyCostUsd * r.count).toLocaleString()}
                </TableCell>
                <TableCell className="text-xs text-muted-foreground max-w-xs">{r.rationale}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
};
